Feature/get units time
fenfisdi/cdslab_agents_config_api pull request #1
Opened 2021-06-02 20:03 UTC by dcorquir

Added function and endpoint to get units time.

2021-06-03 22:41 UTC, davisfelipe requested changes
Hi Diego

I made suggestions in your code, tell me if you need something.

Greetings

2021-06-03 22:41 UTC, davisfelipe commented on src/routes/test/test_units.py
> +from fastapi.testclient import TestClient
Sort Imports

2021-06-03 22:41 UTC, davisfelipe commented on src/utils/messages.py
> +    time: str = "Time units"
Blank Line at the end of the line

2021-06-03 22:41 UTC, davisfelipe commented on src/utils/units.py
> +        return cls.units_time
Blank Line at the end of the line

2021-06-04 14:30 UTC, Camilo-HG requested changes

2021-06-04 14:30 UTC, Camilo-HG commented on src/utils/units.py
>              "c":"Centimeter"}
"m" instead of "M"
"km" instaed of "Km"
"cm" instead of "c"

Add:
"ft": "feet"
"mi": "international mile"
"yd": "international yard"

2021-06-04 14:30 UTC, Camilo-HG commented on src/utils/units.py
> +        "d": "day"
"days" instead of "day"

2021-06-04 14:34 UTC, davisfelipe approved these changes
### Approved

2021-06-04 16:35 UTC, Camilo-HG approved these changes

2021-06-04 16:35 UTC, merged