Config
fenfisdi/cdslab_agents_config_api pull request #2
Opened 2021-06-03 17:09 UTC by miguelgomezg

2021-06-03 21:51 UTC, davisfelipe commented on src/api.py
> +app.include_router(distributions_routes)
Blank Line at the end of the line

2021-06-03 21:52 UTC, davisfelipe commented on src/interfaces/__init__.py
> +__all__ = ["DistributionInterface"]
Blank Line at the end of the line

2021-06-03 21:54 UTC, davisfelipe commented on src/models/db/Distribution.py
> +    type = ListField(required=True)
Blank Line at the end of the line

2021-06-03 21:54 UTC, davisfelipe commented on src/routes/__init__.py
>  ]
Blank Line at the end of the line

2021-06-03 21:56 UTC, davisfelipe commented on src/routes/distributions.py
> +
Sort Imports
```suggestion
from src.utils import (
        BsonObject,
        UJSONResponse,
        DistributionMessage
 )

```

2021-06-03 21:57 UTC, davisfelipe commented on src/routes/distributions.py
> +        )
Identation
```suggestion
        return UJSONResponse(
            DistributionMessage.not_found, 
            HTTP_404_NOT_FOUND
        )
```

2021-06-03 21:59 UTC, davisfelipe commented on src/routes/distributions.py
> +    )
Blank Line at the end of the line

2021-06-03 22:01 UTC, davisfelipe commented on src/routes/test/test_units.py
> +from fastapi.testclient import TestClient
Sort Import, remeber [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)
```suggestion
from unittest import TestCase

from fastapi.testclient import TestClient
```

2021-06-03 22:01 UTC, davisfelipe commented on src/utils/__init__.py
> +]
Blank Line at the end of the line

2021-06-03 22:02 UTC, davisfelipe commented on src/utils/messages.py
> +    not_exist: str = 'Distribution does not exist'
Blank Line at the end of the line

2021-06-03 22:03 UTC, davisfelipe commented on src/api.py
> +    distributions_routes)
```suggestion
from src.routes import (
    units_routes, 
    distributions_routes
)
```

2021-06-03 22:20 UTC, davisfelipe commented on src/interfaces/distribution_interface.py
> +                ).first()
```suggestion
        return Distribution.objects(
            **filters
        ).first()
```

2021-06-03 22:23 UTC, davisfelipe commented on src/routes/test/test_units.py
> +    def setUp(self) -> None:
2 blank spaces after base declarations
```suggestion
    return ".".join([source, path])


class GetUnitsRouteTestCase(TestCase):
    def setUp(self) -> None:
```

2021-06-03 22:24 UTC, davisfelipe commented on src/models/db/Simulation.py
> +    executed_at = DateField(required=True)
Blank Line at the end of the line

2021-06-03 22:25 UTC, davisfelipe commented on src/models/db/Simulation.py
> +    identifer = UUIDField(unique=True)
it could be named _uuid_, what do you think?

2021-06-03 22:30 UTC, davisfelipe commented on src/routes/test/test_units.py
> +        self.assertEqual(response.status_code, 200)
Blank Line at the end of the line

2021-06-03 22:31 UTC, davisfelipe requested changes
Hi Miguel

I made suggestions in your code, tell if you need something

greetings

2021-06-04 14:14 UTC, Camilo-HG approved these changes

2021-06-04 14:37 UTC, merged