Feature/distributions
fenfisdi/cdslab_agents_config_api pull request #4
Opened 2021-06-07 13:39 UTC by dcorquir

Create endpoint to distributions

2021-06-08 16:35 UTC, davisfelipe requested changes
I made comments on your code.

2021-06-08 16:35 UTC, davisfelipe commented on src/api.py
> +    distributions_routes)
set line break before parentheses

2021-06-08 16:35 UTC, davisfelipe commented on src/utils/units.py
> +        return cls.units_time
Line brake at the end of the file

2021-06-10 21:20 UTC, Camilo-HG requested changes

2021-06-10 21:20 UTC, Camilo-HG commented on src/routes/distributions.py
> +        Disease state distributions object list
Change: "Disease state" ---> "Disease states"

2021-06-10 21:46 UTC, merged