Feature/create new agents configuration
fenfisdi/cdslab_agents_config_api pull request #7
Opened 2021-06-09 13:09 UTC by dcorquir

Added endpoint to create and update agents configuration

2021-06-09 16:28 UTC, davisfelipe requested changes
Hi Diego, I made comments on your code.

Remeber we use [reST Docstring](https://www.python.org/dev/peps/pep-0287) format

2021-06-09 16:28 UTC, davisfelipe commented on src/models/general/simulation.py
> +    ERROR: str = 'error'
Line Break at the end of the file

2021-06-09 16:28 UTC, davisfelipe commented on src/models/db/configuration.py
> +from mongoengine import (
Sort Imports [PEP8 Import](https://www.python.org/dev/peps/pep-0008/#imports)
1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

2021-06-09 16:28 UTC, davisfelipe commented on src/models/__init__.py
> +]
Line Break at the end of the line

2021-06-09 16:28 UTC, davisfelipe commented on src/interfaces/tests/test_configuration_interface.py
> +from src.models import Configuration
Sort Imports

2021-06-09 16:28 UTC, davisfelipe commented on src/interfaces/disease_states_interface.py
> +        return MasterDiseaseStates.objects().all()
Line break at the end of the line

2021-06-09 16:28 UTC, davisfelipe commented on src/interfaces/configuration_interface.py
> +        return Configuration.objects().objects().all()
Why do you call this object twice?

2021-06-10 22:23 UTC, Camilo-HG commented
@davisfelipe aren't we using [numpy docs](https://numpydoc.readthedocs.io/en/latest/format.html) ???

2021-06-10 22:25 UTC, dcorquir commented
> 
> 
> @davisfelipe aren't we using [numpy docs](https://numpydoc.readthedocs.io/en/latest/format.html) ???

Yes we're using numpydocs.

2021-06-10 22:26 UTC, Camilo-HG commented
But you said: "Remeber we use reST Docstring format"

2021-06-10 22:27 UTC, dcorquir commented
> 
> 
> But you said: "Remeber we use reST Docstring format"

Yes, but on code comments we're using numpy structure.

2021-06-10 22:44 UTC, davisfelipe commented
We didn't use Numpy Doc, because:

1. Numpy is better for libraries or independent components, in API Rest we used to write reST Docstring, because is short and precise, Numpy is very extensive for a simple comment.
3. PEP8 Recommend use this format, it is very intuitive. 
2. In FastAPI endpoints, we use reST Docstring to describe endpoints and it information show in OpenAPI and ReDoc.

2021-06-10 23:00 UTC, Camilo-HG commented
Ok. I got it.

2021-06-10 23:05 UTC, Camilo-HG requested changes

2021-06-10 23:05 UTC, Camilo-HG commented on src/routes/configuration.py
> +    Get all configuration exist in db
Change: "Get all configurations exists in db" ---> "Get all existing configurations in db"

2021-06-11 14:07 UTC, merged