Save update
fenfisdi/cdslab_agents_config_api pull request #8
Opened 2021-06-15 19:16 UTC by dcorquir

2021-06-15 20:22 UTC, davisfelipe approved these changes
Nice

2021-06-16 12:38 UTC, Camilo-HG requested changes

2021-06-16 12:38 UTC, Camilo-HG commented on src/interfaces/distribution_interface.py
>          Find all distributions in BD
Change: BD ---> DB

2021-06-16 12:38 UTC, Camilo-HG commented on src/routes/configuration.py
> +    :param configuration: Configuration object to insert in bd
Change: bd ---> db

2021-06-16 12:38 UTC, Camilo-HG commented on src/routes/configuration.py
> +    :param configuration: Configuration object to insert in bd
Change: bd ---> db

2021-06-16 12:38 UTC, Camilo-HG commented on src/routes/distributions.py
> +    :pram name: distribution name
Change: pram ---> param

2021-06-16 14:56 UTC, merged